services:
  app:
    build: ./app
    container_name: mspr-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mspr
      - API_KEY=healthai_key
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./data:/data

  db:
    image: postgres:15
    container_name: mspr-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mspr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mspr"]
      interval: 5s
      timeout: 5s
      retries: 5
  

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: mspr-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://user:password@db:5432/mspr?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: mspr-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # volume persistan
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'  # chemin de stockage persistant

  grafana:
    image: grafana/grafana
    container_name: mspr-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  etl:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: mspr-etl
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mspr
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
      - ./data:/data
    command: ["python", "main.py"]

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
