name: ci
on:
  push:
    branches:
      - main # Déclenche l'action lors d'un push sur la branche principale

permissions:
  contents: write # Autorise l'écriture pour pousser sur la branche gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupération du code source
      - uses: actions/checkout@v4

      # 2. Configuration de l'environnement Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Cache des dépendances pour accélérer les futurs builds
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      # 4. Installation de MkDocs et du thème Material (standard open-source)
      - run: pip install mkdocs-material

      # 5. Déploiement automatique
      # Cette commande build le site et pousse le HTML vers la branche 'gh-pages'
      - run: mkdocs gh-deploy --force
